# .bashrc

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

export http_proxy="http://myuser:passwd123\$@1.3.2.9:1234"
export https_proxy="http://myuser:passwd123\$@1.3.2.9:1234"
export no_proxy="localhost,127.0.0.0/8,12.1.0.0/12,12.18.0.0./16,127.0.0.1"
